### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by jtom2388** [Cris415/infinitePX#3]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by Cris415** [comment]
Hello, what do I need to change in the state to fulfill the following issue? 
> All keys within the values in the state are accessible in the schema

**Comment by jtom2388** [comment]
I noticed you have a table for **follows**, but you don't have a slice of state for it. How do you plan to implement followers for each user?

**Comment by Cris415** [comment]
Ok I wasn't sure how to store follows in the frontend state. But after thinking about it, it makes sense to add a section of state for the follows.
